version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
  build:
    executor:
      name: node/default
    steps:
      - checkout
  server_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          name: Install server
          command: npm install
          working_directory: ./server
      - run:
          name: Running server tests
          command: npm test
          working_directory: ./server
          
  client_test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install client
          command: npm install
          working_directory: ./client
      - run:
          name: Running server tests
          command: npm test
          working_directory: ./client
workflows:
    build-and-test:
      jobs:
        - build
        - server_test:
            requires:
                - build
        - client_test:
            requires:
                - build
