version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dirr: ./server
      - node/install-packages:
          app-dirr: ./client
      - run:
          name: SERVER- Install
          command: npm install
          working_directory: ./server
      - run:
          name: CLIENT- Install
          command: npm install
          working_directory: ./client
      - run:
          name: SERVER- Running tests
          command: npm test
          working_directory: ./server
      - run:
          name: CLIENT- Running tests
          command: npm test
          working_directory: ./client
workflows:
    build-and-test:
      jobs:
        - build-and-test
