version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker
      
  server_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          name: Install server
          command: npm install
          working_directory: ./server
      - run:
          name: Running server tests
          command: npm test
          working_directory: ./server
          
  client_test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install client
          command: npm install
          working_directory: ./client
      - run:
          name: Running server tests
          command: npm test
          working_directory: ./client
  docker_image_build:
    machine: true
    steps:
      - checkout          
      - run:
          name: Build and push database_image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "enzolorenzo" --password-stdin
            sudo docker build ./db -t database_image
            sudo docker push enzolorenzo/ask-lab2-ci-cd-docker:database_image
      - run:
          name: Build and push server_image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "enzolorenzo" --password-stdin
            sudo docker build ./server -t server_image
            sudo docker push enzolorenzo/ask-lab2-ci-cd-docker:server_image
      - run:
          name: Build and push client_image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "enzolorenzo" --password-stdin
            sudo docker build ./client -t client_image
            sudo docker push enzolorenzo/ask-lab2-ci-cd-docker:client_image
workflows:
    build-and-test:
      jobs:
        - build:
          filters:
            branches:
              only:
                - master
        - server_test:
            filters:
              branches:
                only:
                  - master
            requires:
                - build
        - client_test:
            filters:
              branches:
                only:
                  - master
            requires:
                - build
        - docker_image_build:
            requires:
              - server_test
              - client_test
